[profile.default]
fail-fast = false
slow-timeout = { period = "60s", terminate-after = 5, grace-period = "30s" }

[profile.ci]
failure-output = "immediate-final"
fail-fast = false
slow-timeout = { period = "60s", terminate-after = 5, grace-period = "30s" }

